export const products = [
  {
    id: 101,
    title: "Meowloha",
    description: "Buy it now and taste heaven",
    price: 500,
    stock: 112,
    img: "https://res.cloudinary.com/dwzbz3j4q/image/upload/v1686596193/comision-43240/d71d8f5d1a590c05e16e7f0eaa0bc37f_oxhjxj.png",
    category: "Catnip Barato",
  },
  {
    id: 102,
    title: "Meowabonga",
    description: "Try this to know the glory",
    price: 1000,
    stock: 123,
    img: "https://res.cloudinary.com/dwzbz3j4q/image/upload/v1686658877/comision-43240/gray-tabby-cat-sniffing-catnip-600w-1750474934_o9vjot.jpg",
    category: "Catnip Barato",
  },
  {
    id: 103,
    title: "Meowrale",
    description: "This is a sentence to paradise with tequila",
    price: 1500,
    stock: 134,
    img: "https://res.cloudinary.com/dwzbz3j4q/image/upload/v1686658920/comision-43240/gray-cat-enjoying-fresh-catnip-600w-688656943_alkdzs.jpg",
    category: "Catnip Barato",
  },
  {
    id: 104,
    title: "Meowla Pirola",
    description: "Don't forget your mate with this",
    price: 2000,
    stock: 145,
    img: "https://res.cloudinary.com/dwzbz3j4q/image/upload/v1686658938/comision-43240/friss-macskamenta-macska-_C3_A9s-v_C3_A1za_zbcuaw.jpg",
    category: "Catnip Barato",
  },
  {
    id: 105,
    title: "Meownda la osa",
    description: "Available at Moe's",
    price: 2500,
    stock: 156,
    img: "",
    category: "Catnip del Bueno",
  },
  {
    id: 106,
    title: "Meow",
    description: "Meow",
    price: 3000,
    stock: 167,
    img: "",
    category: "Catnip del Bueno",
  },
  {
    id: 107,
    title: "Meowlala",
    description: "Bring your own bagette",
    price: 3500,
    stock: 178,
    img: "",
    category: "Catnip del Bueno",
  },
  {
    id: 108,
    title: "Meowmamia",
    description: "Bring your pizza",
    price: 4000,
    stock: 189,
    img: "",
    category: "Catnip del rebueno",
  },
  {
    id: 109,
    title: "Meowbye",
    description: "Hahahahahahahaha",
    price: 4500,
    stock: 190,
    img: "",
    category: "Catnip del rebueno",
  },
  {
    id: 110,
    title: "Meowboy",
    description: "Meowidy meow",
    price: 5000,
    stock: 200,
    img: "",
    category: "Catnip del rebueno",
  },
];
